# This file created by conda-build 2.1.15
# meta.yaml template originally from:
# /io/tensorflow-gpu, last modified Fri Aug  4 21:43:23 2017
# ------------------------------------------------

package:
    name: tensorflow-gpu
    version: 1.2.1
source:
    fn: tensorflow-1.2.1.tar.gz
    patches:
        - 10366.patch
        - stable-image-rotate-test.patch
        - relax-tolerence-in-special_math_test.patch
        - skip-read-only-debugger_cli_common-test.patch
        - larger-tolerence-in-linalg_grad_test.patch
        - 10522.patch
        - update-highwayhash.patch
    sha256: f2baf09b1a9a0500907b4d5cb5473070b3ecede06ed6e8d1096873c91922fb9e
    url: https://github.com/tensorflow/tensorflow/archive/v1.2.1.tar.gz
build:
    entry_points:
        - tensorboard = tensorflow.tensorboard.tensorboard:main
    noarch: ''
    noarch_python: false
    number: '0'
    script_env:
        - CUDA_VERSION
        - CUDNN_VERSION
    string: py27cuda8.0cudnn6.0_0
requirements:
    build:
        - markdown 2.6.8 py27_0
        - werkzeug 0.12.2 py27_0
        - libprotobuf 3.2.0 0
        - wheel 0.29.0 py27_0
        - scikit-learn 0.18.1 np112py27_1
        - pbr 1.10.0 py27_0
        - bazel 0.4.5 0
        - funcsigs 1.0.2 py27_0
        - openssl 1.0.2l 0
        - mock 2.0.0 py27_0
        - sqlite 3.13.0 0
        - cudatoolkit 8.0 0
        - python 2.7.13 0
        - zlib 1.2.8 3
        - numpy 1.12.1 py27_0
        - cudnn 6.0.21 0
        - swig 3.0.10 0
        - backports.weakref 1.0rc1 py27_0
        - protobuf 3.2.0 py27_0
        - bleach 1.5.0 py27_0
        - scipy 0.19.0 np112py27_0
        - setuptools 27.2.0 py27_0
        - html5lib 0.9999999 py27_0
        - backports 1.0 py27_0
        - portpicker 1.1.1 py27_0
        - six 1.10.0 py27_0
        - pip 9.0.1 py27_1
        - pcre 8.39 1
        - openblas 0.2.19 0
    run:
        - python
        - werkzeug >=0.11.10
        - six >=1.10.0
        - protobuf >=3.2.0
        - numpy >=1.12
        - mock >=2.0.0
        - markdown >=2.6.8
        - html5lib ==0.9999999
        - bleach ==1.5.0
        - backports.weakref ==1.0rc1
        - cudatoolkit 8.0*
        - cudnn 6.0*
test:
    commands:
        - conda inspect linkages -p $PREFIX tensorflow-gpu
    files:
        - gpu_test.py
about:
    description: 'TensorFlow provides multiple APIs.The lowest level API, TensorFlow
        Core

        provides you with complete programming control.

        '
    dev_url: https://github.com/tensorflow/tensorflow
    doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src
    doc_url: https://www.tensorflow.org/get_started/get_started
    home: http://tensorflow.org/
    license: Apache 2.0
    license_family: Apache
    summary: TensorFlow is a machine learning library
extra:
    final: true
