channels:
  sources:
    - loopbio
    - conda-forge
    - intel
    - defaults
  targets:
    - [loopbio, main]

github:
  user_or_org: 'loopbio'

docker:
  image: sdvillal/linux-anvil-cudnn
  executable: nvidia-docker
